# Generated by Django 4.0.4 on 2022-05-23 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testmodel',
            name='colour',
            field=models.CharField(default='Blue', max_length=200),
            preserve_default=False,
        ),
    ]
